#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3'
services:
  node:
    # Uncomment the next line to use a non-root user. On Linux, this will prevent
    # new files getting created as root, but you may need to update the USER_UID
    # and USER_GID in .devcontainer/Dockerfile to match your user if not 1000.
    # user: node

    build: 
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ..:/workspace
      - ~/.ssh:/root/.ssh-localhost:ro
      # Volumes to mount the node_modules folder to speed up yarn/npm usage on each project
      - 01-desafio-node_modules:/workspace/01-desafio/node_modules
      - 02-gobarber-node_modules:/workspace/02-iniciando-back-end-do-gobarber/node_modules
      - 02-desafio-node_modules:/workspace/02-desafio/node_modules
      - 03-gobarber-node_modules:/workspace/03-continuando-api-do-gobarber/node_modules
      - 03-desafio-node_modules:/workspace/03-desafio/node_modules
      - 04-react-node_modules:/workspace/04-introducao-ao-react/node_modules
      - 04-desafio-node_modules:/workspace/04-desafio/node_modules

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    ports:
      - "3000:3000"
      - "8080:8080"
    
    links:
      - postgresdb
      - mongobarber

  postgresdb:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gobarber

  mongobarber:
    image: mongo
    ports:
      - "27017"

  redisbarber:
    image: redis:alpine
    ports:
      - "6379"

volumes:
  01-desafio-node_modules:
  02-gobarber-node_modules:
  02-desafio-node_modules:
  03-gobarber-node_modules:
  03-desafio-node_modules:
  04-react-node_modules:
  04-desafio-node_modules:
