#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3'
services:
  node:
    # Uncomment the next line to use a non-root user. On Linux, this will prevent
    # new files getting created as root, but you may need to update the USER_UID
    # and USER_GID in .devcontainer/Dockerfile to match your user if not 1000.
    # user: node

    build: 
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ..:/workspace
      - ~/.ssh:/root/.ssh-localhost:ro

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    ports:
      - "3000:3000"
    
    links:
      - postgresdb
      - mongobarber

  postgresdb:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gobarber

  mongobarber:
    image: mongo
    ports:
      - "27017"

  redisbarber:
    image: redis:alpine
    ports:
      - "6379"
